apiVersion: v1
kind: Deployment
metadata:
  name: query_bot
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit_container
          image: manjunadh876/streamlit:v1
          ports:
          - containerPort: 8501
          env:
          - name: token
            valueFrom: 
              secretKeyRef:
                name: k8-secret
                key: token
---
apiVersion: v1
kind: Service
metadata:
  name: query_bot
spec:
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501