apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: botcontainer
          image: manjunadh876/streamlit:v1
          ports:
          - containerPort: 8501
          env:
          - name: token
            valueFrom:
              secretKeyRef:
                name: k8-secret
                key: token
---
apiVersion: v1
kind: Service
metadata:
  name: bot
spec:
  selector:
    app: bot
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
